### ISSUE TITLE
sdk.order.sell not working for TEZOS

### ISSUE THREAD

**Issue by vicwtang** [rarible/protocol#347]
As a result of https://github.com/rarible/sdk/issues/225, I had to manually update every token created by calliing sdk.order.sell.
While this worked fine for ETHEREUM lazy minted NFTs, ALL calls to sell TEZOS tokens failed. After a lengthy timeout, I received:
Error: Confirmation polling timed out
    at SwitchMapSubscriber.project (C:\dev\batchMinter\node_modules\@taquito\taquito\dist\taquito.umd.js:598:185)  
    at SwitchMapSubscriber._next (C:\dev\batchMinter\node_modules\rxjs\internal\operators\switchMap.js:47:27)      
    at SwitchMapSubscriber.Subscriber.next (C:\dev\batchMinter\node_modules\rxjs\internal\Subscriber.js:66:18)     
    at ReplaySubject.Subject.next (C:\dev\batchMinter\node_modules\rxjs\internal\Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (C:\dev\batchMinter\node_modules\rxjs\internal\ReplaySubject.js:50:31) 
    at BatchOperation.<anonymous> (C:\dev\batchMinter\node_modules\@taquito\taquito\dist\taquito.umd.js:659:38)    
    at Generator.next (<anonymous>)
    at C:\dev\batchMinter\node_modules\@taquito\taquito\dist\taquito.umd.js:44:75
    at new Promise (<anonymous>)
    at __awaiter (C:\dev\batchMinter\node_modules\@taquito\taquito\dist\taquito.umd.js:40:16)

my request:
    const currency = {
        'TEZOS': "XTZ",
        "ETHEREUM": "ETH",
        "POLYGON": "MATIC",
    }
    console.log('calling order.sell')
    const sellAction = await sdk.order.sell({
        itemId: itemInfo.itemId
    })

    let orderId
    console.log('calling submit')
    try {
        sellAction.submit({
            amount: 1,
            price: priceStr,
            currency: {
                "@type": currency[blockchain],
            },
            // payouts: [{
            //     account: sellerUnionAddress,
            //     value: 10000,
            // }],
        }).then(orderId => {

...

**Comment by eduardstal** [comment]
@ex1st0r testing something, please ignore.

**Comment by ex1st0r** [comment]
Hi!
Try mintAndSell with @rarible/sdk 0.9.5 version, it should work. And also you can check tests on mint-sell https://github.com/rarible/sdk/blob/master/packages/sdk/src/sdk-blockchains/tezos/mint-and-sell.test.ts

**Comment by vicwtang** [comment]
Hi Eduard

I just attempted this call for my Tezos nft's and am getting timeout
errors. Similarly, calling your api
https://api.rarible.org/v0.1/items/byOwner?owner=TEZOS:tz1faBsSSSNj1iKnwzr....8EmZdU5kCn&size=25&includeMeta=true
resulted in {"code":"UNKNOWN","message":"nested exception is
io.netty.handler.timeout.ReadTimeoutException"}

the Tezos items/byOwner call has been unavailable for a while. Is there a
fundamental issue with Tezos?
My package.json:
        ***@***.***/ethers-ethereum": "^0.12.66",
        ***@***.***/sdk": "^0.9.6",
        ***@***.***/sdk-wallet": "^0.9.6",
        ***@***.***/web3-ethereum": "^0.12.66",
        "tezos-sdk-module": "^0.0.52",

Please advise. I've currently over 1000 tezos nft's minted, most of which I
cannot list for sale.
Thanks
Vic

sdk.order.sell results:
{
  tzpk: '...'
} { tzuri: 'https://mainnet.api.tez.ie' }
{
  itemId: 'TEZOS:KT1X8EiYF9tomiDVGagMV8ubrEhpqRfXEq1b:1002',
}
calling sellItem
calling order.sell
calling submit
{
  err: Error: Confirmation polling timed out
      at SwitchMapSubscriber.project
***@***.***\taquito\dist\taquito.umd.js:600:185)
      at SwitchMapSubscriber._next
(C:\dev\batchMinter.bak\node_modules\rxjs\internal\operators\switchMap.js:47:27)

      at SwitchMapSubscriber.Subscriber.next
(C:\dev\batchMinter.bak\node_modules\rxjs\internal\Subscriber.js:66:18)
      at ReplaySubject.Subject.next
(C:\dev\batchMinter.bak\node_modules\rxjs\internal\Subject.js:60:25)
      at ReplaySubject.nextInfiniteTimeWindow
(C:\dev\batchMinter.bak\node_modules\rxjs\internal\ReplaySubject.js:50:31)
      at BatchOperation.<anonymous>
***@***.***\taquito\dist\taquito.umd.js:661:38)

      at Generator.next (<anonymous>)
      at
***@***.***\taquito\dist\taquito.umd.js:44:75
      at new Promise (<anonymous>)
      at __awaiter
***@***.***\taquito\dist\taquito.umd.js:40:16)
      at BatchOperation.confirmation
***@***.***\taquito\dist\taquito.umd.js:656:20)

      at
***@***.***\tezos-sdk\dist\providers\in_memory\in_memory_provider.js:116:69

      at step
***@***.***\tezos-sdk\dist\providers\in_memory\in_memory_provider.js:44:23)
      at Object.next
***@***.***\tezos-sdk\dist\providers\in_memory\in_memory_provider.js:25:53)
      at
***@***.***\tezos-sdk\dist\providers\in_memory\in_memory_provider.js:19:71

      at new Promise (<anonymous>)
}

**Comment by evgenynacu** [comment]
We are discontinuing Tezos support
https://discord.com/channels/1020069477490118748/1093554014840434708/1179413887959961671

So closing this issue
