### ISSUE TITLE
Mint transactions failing due to underpricing on Polygon

### ISSUE THREAD

**Issue by vicwtang** [rarible/protocol#349]
PLEASE NOTE this issue is urgent - backend minting to POLYGON is effectively dead at the moment

There appears to be no reliable method to set the gas for a sdk.nft.mint or any other API call as one cannot directly affect the sendTx.
As a result, on both a backend server AND on a DAPP, the request often FAILS due to underpriced transaction.
On a DAPP, the gas price defaulted to is BELOW even the METAMASK low price. However, an advanced user is able to override in the METAMASK ui and select Market or Aggressive pricing. On a backend server, this is not an option.

as a result, backend server sdk.nft.mint call frequently gets the underpriced response show below.
I was pointed to using the Web3 package instead of ethers:
	const feeData = await provider.getFeeData()
	const web3 = new Web3(provider)
	const web3Options = { web3, from: account.address, 
		maxFeePerGas: feeData.maxFeePerGas, 
		maxPriorityFeePerGas: feeData.maxPriorityFeePerGas}
	const web3Ethereum = new Web3Ethereum(web3Options)
	return new EthereumWallet(web3Ethereum)

However, this did not improve the likelihood of the mint transaction succeeding. There is no way to set a wallet level gas preference in ETHERS.

Please advise how I can improve the chances of a Polygon mint action succeeding. Preferably, being able to set the MM market price values as the default in both DAPP and server backend settings would be ideal

Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":53,\"error\":{\"code\":-32000,\"message\":\"transaction underpriced\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\".....\"],\"id\":53,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://rpc-mainnet.maticvigil.com/v1/28017641955d686a58ba50ff4ee593d9d1ad6ea9", code=SERVER_ERROR, version=web/5.6.0)  
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","id":53,"error":{"code":-32000,"message":"transaction underpriced"}}',
  error: Error: transaction underpriced
      at getResult (C:\dev\batchMinter\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:170:21)      
      at processJsonFunc (C:\dev\batchMinter\node_modules\@ethersproject\web\lib\index.js:348:22)
      at C:\dev\batchMinter\node_modules\@ethersproject\web\lib\index.js:280:46
      at step (C:\dev\batchMinter\node_modules\@ethersproject\web\lib\index.js:33:23)
      at Object.next (C:\dev\batchMinter\node_modules\@ethersproject\web\lib\index.js:14:53)
      at fulfilled (C:\dev\batchMinter\node_modules\@ethersproject\web\lib\index.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: -32000,
    data: undefined
  },

**Comment by bobwith2bees** [comment]
@vicwtang I am looking at calling the ERC-721 contact directly in cases where the Rarible SDK and Protocol Endpoints are down; however I am not finding a documented way to do this from a web3 call just yet.  If they shared the source for the  mint endpoints that would help us both understand how to do it ourselves as well as potentially provide a solution for your issue (and propose a fix etc.)

**Comment by bin0316** [comment]
> 

I got same problem on polygon network.
When I try to purchase order by using this code, I get "transaction underpriced" error too.


import { createRaribleSdk } from "@rarible/protocol-ethereum-sdk"

const sdk = createRaribleSdk(web3, env, { fetchApi: fetch })
sdk.order.buy({ order, payouts: [], originFees: [], amount: 1, infinite: true })

**Comment by vicwtang** [comment]
Hi. I'm actively working w Rarible to get the gas estimation working for
their contract method calls.
However, from the DAPP which Im guessing you are most likely using, the
user has the option when the wallet pops up to request confirmation, to
manually choose a gas options (low, market, aggressive)
This will usually force ti thru.
On the backend, there is currently no solution available to my knowledge
despite my best efforts without a rarible sdk fix

**Comment by vicwtang** [comment]
Ha. You're in the same boat as me then. Love to collaborate as it doesnt seem there are many of us???

Update. This is also occurring on mumbai now. Although in this case it got as pending, its not being processed with the fee too low: Uncaught (in promise) Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Be aware that it might still be mined!
    at Object.TransactionError (errors.js?469f:87:1)
    at eval (index.js?f0d1:426:1)

**Comment by vicwtang** [comment]
I've moved to my own polygon contract and have been able to reliably mint that way.
I've also found that I can call my rarible delegate proxy to query ownership, so perhaps i can call mint directly if the abi for it is the same as the standard 721 mint function, and hence set my own gas? haven't tried it yet - fixing other fires...

**Comment by ex1st0r** [comment]
"transaction underpriced" error means that your provider estimate gas not correctly, probably it's cannot working with EIP-1559
Check our example for minting on backend on mumbai network (also you can check on mainnet): https://github.com/rarible/sdk/blob/master/packages/sdk/example/backend/polygon/mint.ts and take "initNodeProvider" function to initialize provider in your code. Look at our TestSubprovider in [that file](https://github.com/rarible/sdk/blob/master/packages/sdk/example/backend/common.ts) that using in mint example - it's a our version of WalletSubprovider from [web3-provider-engine](https://github.com/MetaMask/web3-provider-engine) package.
<br/>
But if your code on frontend and you faced with that error, try to use our middleware from @rarible/estimate-middleware package: just call "estimate" function with your provider ([see more in test](https://github.com/rarible/ts-common/blob/master/packages/estimate-middleware/src/index.test.ts))

**Comment by vicwtang** [comment]
Question: on the dapp, I am currently utilizing
the InjectedWeb3ConnectionProvider. I don't imagine this is updated as well
to use the estimator?
Would I extend from that in order to replace the initialization code for
the web3 object?

**Comment by vicwtang** [comment]
On closer review, the InjectedWeb3ConnectionProvider grabs the web3 object instantiated by the metamask wallet. So...am I supposed to replace that with one that calls? Should I be creating my own connection object to pass to CreateRaribleSDK?

**Comment by vitalbadjo** [comment]
@vicwtang on nodejs backend for Polygon you can use ethers (initWallet function in [this](https://github.com/rarible/sdk/blob/master/packages/sdk-examples/src/backend/common.ts) example) or web3js with "estimate" from @rarible/estimate-middleware package, both of them correctly handle gas fees for polygon. On frontend side

**Comment by vicwtang** [comment]
Thanks Vitali
I will do some testing over the next few days. In particular i need this to
work from the backend where it fails 80% of the time due to insufficient
gas.
On the UI, i currently can adjust the gas in metamask - the my current
ethers implementation still aways underprices but I can review your test
example.

**Comment by vicwtang** [comment]
Just noticed the sdk/example app for the first time. A great reference
example and will be most helpful.
However, I also tried to mint to polygon production and staging - they both
failed, this time with error: Request rejected
The method "eth_maxPriorityFeePerGas" does not exist / is not available.
This is only a tangentially related issue - we're unable to set
maxPriorityFeePerGas...
Please advise...
Thx
