### ISSUE TITLE
revert order signature verification error

### ISSUE THREAD

**Issue by mekery** [rarible/protocol#395]
Hi guys,

I'm trying to deploy protocol-contracts on local Ganache network, and build a Dapp using js code following ethereum-sdk, when perform buy action (fillOrder), Metamask say there might be an error in the contract, the error is "revert order signature verification error".

```json
{
    "value": {
        "code": -32603,
        "data": {
            "message": "VM Exception while processing transaction: revert order signature verification error",
            "code": -32000,
            "data": {
                "0x87cb9ff08965df1e94c5ed5eb77de42f29199b9c2385adb869e89f48cf97af65": {
                    "error": "revert",
                    "program_counter": 889,
                    "return": "0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000226f72646572207369676e617475726520766572696669636174696f6e206572726f72d3d121875b469dd528876b3a27d38a3a4d12bcb674266becb80100000000",
                    "reason": "order signature verification error"
                },
                "stack": "RuntimeError: VM Exception while processing transaction: revert order signature verification error\n    at Function.RuntimeError.fromResults (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)\n    at BlockchainDouble.processBlock (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/blockchain_double.js:627:24)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
                "name": "RuntimeError"
            }
        }
    }
}
```

What might be the problem?

The Dapp works when I use the contract address from config of [testnet](https://github.com/rarible/ethereum-sdk/blob/master/packages/sdk/src/config/testnet.ts) in Rinkeby network.

**Comment by mekery** [comment]
> Hi! Our testnet now is on Goerli network. Check chainId of your Ganache instance (chainId=5)

Thanks for you reply.

Now I deploy it on Goerli network, everythings works.
